variable "key_name" {}
variable "ami_id" {}
variable "instance_type" {}
variable "instance_count" {}
variable "name_prefix" {}
variable "name" {}
variable "associate_public_ip_address" {}
variable "root_volume_size" {}
variable "ebs_name" {}
variable "required_public_eip" {}
variable "subnet_id" {}
variable "iam_instance_profile" {}
variable "sg_id" {}